package testlayout;

/**
 *
 * @author leanh
 */
public class Cal extends javax.swing.JFrame {

        /**
         * Creates new form SimpleCalculator
         */
        public Cal() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                java.awt.GridBagConstraints gridBagConstraints;

                Label1_236 = new javax.swing.JLabel();
                TextField1_236 = new javax.swing.JTextField();
                Label2_236 = new javax.swing.JLabel();
                TextField2_236 = new javax.swing.JTextField();
                Label3_236 = new javax.swing.JLabel();
                TextField3_236 = new javax.swing.JTextField();
                Button1_236 = new javax.swing.JButton();
                Button2_236 = new javax.swing.JButton();
                Button3_236 = new javax.swing.JButton();
                Button4_236 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("SimpleCalculator");
                getContentPane().setLayout(new java.awt.GridBagLayout());

                Label1_236.setText("Số thứ nhất");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
                getContentPane().add(Label1_236, gridBagConstraints);

                TextField1_236.setPreferredSize(new java.awt.Dimension(200, 25));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 0;
                gridBagConstraints.gridwidth = 3;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
                getContentPane().add(TextField1_236, gridBagConstraints);

                Label2_236.setText("Số thứ nhất");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridy = 1;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
                getContentPane().add(Label2_236, gridBagConstraints);

                TextField2_236.setPreferredSize(new java.awt.Dimension(200, 25));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 1;
                gridBagConstraints.gridwidth = 3;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
                getContentPane().add(TextField2_236, gridBagConstraints);

                Label3_236.setText("Kết quả");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridy = 2;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
                getContentPane().add(Label3_236, gridBagConstraints);

                TextField3_236.setEnabled(false);
                TextField3_236.setPreferredSize(new java.awt.Dimension(200, 25));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 2;
                gridBagConstraints.gridwidth = 3;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
                getContentPane().add(TextField3_236, gridBagConstraints);

                Button1_236.setText("+");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 3;
                getContentPane().add(Button1_236, gridBagConstraints);

                Button2_236.setText("-");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 3;
                getContentPane().add(Button2_236, gridBagConstraints);

                Button3_236.setText("*");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 3;
                getContentPane().add(Button3_236, gridBagConstraints);

                Button4_236.setText(":");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 3;
                gridBagConstraints.gridy = 3;
                getContentPane().add(Button4_236, gridBagConstraints);

                pack();
        }// </editor-fold>//GEN-END:initComponents

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(Cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(Cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(Cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(Cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new Cal().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton Button1_236;
        private javax.swing.JButton Button2_236;
        private javax.swing.JButton Button3_236;
        private javax.swing.JButton Button4_236;
        private javax.swing.JLabel Label1_236;
        private javax.swing.JLabel Label2_236;
        private javax.swing.JLabel Label3_236;
        private javax.swing.JTextField TextField1_236;
        private javax.swing.JTextField TextField2_236;
        private javax.swing.JTextField TextField3_236;
        // End of variables declaration//GEN-END:variables
}
